language: node_js
node_js:
  - 12
cache: npm
before_install:
  - export TZ='Asia/Shanghai'
  - git config --global user.name "wwbgo"
  - git config --global user.email "wwbgo@qq.com"
install:
  - npm install -g hexo-cli
  - npm install
script:
  - hexo clean
  - hexo generate
  - hexo deploy
