language: node_js
node_js:
  - 12
cache: npm
before_install:
  - export TZ='Asia/Shanghai'
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo clean
  - hexo generate
after_script:
  - hexo deploy
